export type Focus = 'Full body' | 'Hips' | 'Spine' | 'Balance' | 'Strength' | 'Rest'
export type Difficulty = 'Beginner' | 'Intermediate'

export interface Pose {
  id: string
  name: string
  sanskrit: string
  focus: Focus[]
  difficulty: Difficulty
  benefit: string
  cue: string
  modification: string
  sided?: boolean
}

export const poses: Pose[] = [
  { id: 'mountain', name: 'Mountain', sanskrit: 'Tadasana', focus: ['Balance', 'Full body'], difficulty: 'Beginner', benefit: 'Builds awareness of posture, grounding, and even weight distribution.', cue: 'Stand tall with feet comfortably apart. Soften your knees, relax your shoulders, and let your arms rest by your sides.', modification: 'Stand near a wall or hold the back of a chair for support.' },
  { id: 'upward-salute', name: 'Upward Salute', sanskrit: 'Urdhva Hastasana', focus: ['Spine', 'Full body'], difficulty: 'Beginner', benefit: 'Encourages length through the sides of the body and gentle shoulder mobility.', cue: 'From standing, reach your arms up without lifting your shoulders toward your ears. Keep your ribs relaxed.', modification: 'Keep your hands apart or lift your arms only as high as feels easy.' },
  { id: 'chair', name: 'Chair Pose', sanskrit: 'Utkatasana', focus: ['Strength', 'Balance'], difficulty: 'Beginner', benefit: 'Builds heat and strength in the legs and core while challenging steady, grounded balance.', cue: 'Sink your hips back as if sitting into a chair behind you. Reach your arms up and let your knees track toward your toes.', modification: 'Keep your feet comfortably apart, don’t sink as low, and rest your hands on your thighs.' },
  { id: 'forward-fold', name: 'Standing Forward Fold', sanskrit: 'Uttanasana', focus: ['Spine', 'Hips'], difficulty: 'Beginner', benefit: 'Gently lengthens the back of the legs and invites the upper body to release.', cue: 'Hinge from your hips with bent knees. Let your head and arms hang, keeping your weight balanced through your feet.', modification: 'Rest your hands on blocks or a chair. Bend your knees generously.' },
  { id: 'halfway-lift', name: 'Halfway Lift', sanskrit: 'Ardha Uttanasana', focus: ['Spine', 'Full body'], difficulty: 'Beginner', benefit: 'Lengthens the spine with a flat back and awakens the core and legs.', cue: 'From a forward fold, lift your torso halfway with a long, flat back. Bring your hands to your shins and reach your crown forward.', modification: 'Bend your knees or rest your hands on blocks to keep your back long.' },
  { id: 'wide-legged-forward-fold', name: 'Wide-Legged Forward Fold', sanskrit: 'Prasarita Padottanasana', focus: ['Spine', 'Hips'], difficulty: 'Beginner', benefit: 'Lengthens the back of the legs and spine while encouraging a calm, grounded fold.', cue: 'Step your feet wide, fold from your hips, and let your hands rest on the floor or blocks. Keep your spine long as you release your head toward the mat.', modification: 'Bend your knees and rest your hands on blocks or a chair.' },
  { id: 'downward-dog', name: 'Downward-Facing Dog', sanskrit: 'Adho Mukha Svanasana', focus: ['Full body', 'Strength'], difficulty: 'Beginner', benefit: 'Builds upper-body support and lengthens the spine and back of the legs.', cue: 'Press through your hands and lift your hips up and back. Keep your spine long; your heels do not need to touch the mat.', modification: 'Bend your knees, or place your hands on a sturdy chair instead of the floor.' },
  { id: 'plank', name: 'Plank', sanskrit: 'Phalakasana', focus: ['Strength', 'Full body'], difficulty: 'Intermediate', benefit: 'Develops coordinated strength through the shoulders, core, and legs.', cue: 'Place your shoulders over your wrists. Reach back through your heels and keep your neck in line with your spine.', modification: 'Lower your knees to the mat or practice with your hands on a wall.' },
  { id: 'chaturanga', name: 'Chaturanga', sanskrit: 'Chaturanga Dandasana', focus: ['Strength', 'Full body'], difficulty: 'Intermediate', benefit: 'Builds full-body strength, especially through the arms, core, and legs, while teaching a steady low-plank line.', cue: 'From plank, lower halfway with your elbows hugging your sides. Keep one line from head to heels and pause without sinking your hips.', modification: 'Lower your knees to the mat, or practice holding plank instead.' },
  { id: 'cobra', name: 'Low Cobra', sanskrit: 'Bhujangasana', focus: ['Spine', 'Strength'], difficulty: 'Beginner', benefit: 'Gently mobilizes the upper back and opens the front of the chest.', cue: 'Lie on your belly with hands beside your ribs. Gently lift your chest, keeping elbows bent and little weight in your hands.', modification: 'Lift only a little. Keep your gaze down and stop if your lower back feels compressed.' },
  { id: 'cat', name: 'Cat', sanskrit: 'Marjaryasana', focus: ['Spine'], difficulty: 'Beginner', benefit: 'Encourages gentle spinal flexion and awareness of the back body.', cue: 'On all fours, press the floor away and round your back. Let your head follow naturally without forcing your chin down.', modification: 'Pad your knees or practice seated with hands resting on your thighs.' },
  { id: 'cow', name: 'Cow', sanskrit: 'Bitilasana', focus: ['Spine'], difficulty: 'Beginner', benefit: 'Encourages gentle spinal extension and openness across the chest.', cue: 'On all fours, gently tip your sitting bones up and broaden your chest. Keep the back of your neck long.', modification: 'Use a smaller movement or practice seated. Avoid sinking into your lower back.' },
  { id: 'child', name: 'Child’s Pose', sanskrit: 'Balasana', focus: ['Rest', 'Hips', 'Spine'], difficulty: 'Beginner', benefit: 'Offers a quiet resting shape with gentle length through the back.', cue: 'Bring your hips toward your heels and rest your torso forward. Reach your arms out or rest them beside you.', modification: 'Place a cushion under your forehead or between your hips and heels. Choose a seated rest if kneeling is uncomfortable.' },
  { id: 'warrior-one', name: 'Warrior I', sanskrit: 'Virabhadrasana I', focus: ['Strength', 'Hips', 'Balance'], difficulty: 'Intermediate', benefit: 'Builds standing stability and length through the front of the back hip.', cue: 'Step one foot back, bend your front knee toward your toes, and reach up. Let your hips face forward only as far as comfortable.', modification: 'Shorten your stance and keep hands on hips. Lift the back heel if needed.', sided: true },
  { id: 'warrior-two', name: 'Warrior II', sanskrit: 'Virabhadrasana II', focus: ['Strength', 'Hips', 'Balance'], difficulty: 'Beginner', benefit: 'Develops leg endurance, steady balance, and openness through the hips.', cue: 'Take a wide stance, turn your front toes out, and bend that knee in line with your toes. Open your arms and look past your front hand.', modification: 'Use a shorter stance or support yourself with a chair.', sided: true },
  { id: 'triangle', name: 'Triangle', sanskrit: 'Trikonasana', focus: ['Hips', 'Balance', 'Spine'], difficulty: 'Intermediate', benefit: 'Encourages length through the side body and stability in the legs.', cue: 'From a wide stance, turn your front toes out and reach forward. Rest your lower hand on your shin or a block and open your chest.', modification: 'Keep a soft bend in your front knee and your upper hand on your hip.', sided: true },
  { id: 'tree', name: 'Tree', sanskrit: 'Vrksasana', focus: ['Balance', 'Hips'], difficulty: 'Beginner', benefit: 'Practices single-leg balance, concentration, and standing stability.', cue: 'Shift into one foot. Place your other foot at your ankle or inner calf, away from the knee joint. Find a steady point to look at.', modification: 'Keep the lifted toes on the floor and use a wall for balance.', sided: true },
  { id: 'boat', name: 'Boat Pose', sanskrit: 'Navasana', focus: ['Strength', 'Balance'], difficulty: 'Intermediate', benefit: 'Strengthens the core and hip flexors while encouraging a lifted, steady chest.', cue: 'Sit tall and lean back slightly. Lift your feet off the mat and reach your arms forward, keeping the back of your neck long.', modification: 'Keep your knees bent and hold behind your thighs, or rest your toes on the mat.' },
  { id: 'bridge', name: 'Bridge', sanskrit: 'Setu Bandha Sarvangasana', focus: ['Spine', 'Strength'], difficulty: 'Beginner', benefit: 'Engages the back of the body and gently opens the front of the hips.', cue: 'Lie on your back, knees bent and feet hip-width apart. Press into your feet and lift your hips without turning your head.', modification: 'Lift only as far as comfortable, or keep your hips resting on the mat.' },
  { id: 'fish', name: 'Fish Pose', sanskrit: 'Matsyasana', focus: ['Spine', 'Rest'], difficulty: 'Beginner', benefit: 'Gently opens the chest and front of the body while encouraging a supported lift through the upper back.', cue: 'Lie on your back and press into your forearms to lift your chest. Rest the crown of your head lightly on the mat and keep your legs easy.', modification: 'Keep your chest low and rest your head on a folded blanket. Place a folded blanket or block under your upper back for support.' },
  { id: 'seated-fold', name: 'Seated Forward Fold', sanskrit: 'Paschimottanasana', focus: ['Hips', 'Spine'], difficulty: 'Beginner', benefit: 'Gently lengthens the back of the legs and supports a quieter pace.', cue: 'Sit tall with legs in front. Bend your knees and tip forward from the hips, keeping space through your chest.', modification: 'Sit on a folded blanket. Loop a strap around your feet without pulling.' },
  { id: 'janu-sirsasana', name: 'Head-to-Knee Pose', sanskrit: 'Janu Sirsasana', focus: ['Hips', 'Spine'], difficulty: 'Beginner', benefit: 'Lengthens the back of the extended leg and the spine while inviting a calm, inward focus.', cue: 'Sit with one leg extended and the sole of the other foot resting against your inner thigh. Sit tall as you inhale, then fold forward over the straight leg as you exhale, leading with your chest.', modification: 'Bend the extended knee, sit on a folded blanket, or rest your forehead on a block or cushion.', sided: true },
  { id: 'easy-seat', name: 'Easy Seat', sanskrit: 'Sukhasana', focus: ['Rest', 'Hips'], difficulty: 'Beginner', benefit: 'Creates a comfortable base for breath awareness and quiet attention.', cue: 'Sit cross-legged with your spine comfortably tall. Let your hands and shoulders soften.', modification: 'Sit on a cushion or in a chair with your feet resting on the floor.' },
  { id: 'seated-reach', name: 'Seated Reach', sanskrit: 'Urdhva Hastasana (seated)', focus: ['Spine', 'Full body'], difficulty: 'Beginner', benefit: 'Lengthens the spine and side body from a grounded seat.', cue: 'Sit comfortably and reach both arms up, keeping your shoulders soft and your spine long.', modification: 'Reach one arm at a time, or keep your hands resting on your thighs.' },
  { id: 'neck-roll', name: 'Seated Neck Rolls', sanskrit: 'Griva Sanchalana', focus: ['Spine', 'Rest'], difficulty: 'Beginner', benefit: 'Eases tension in the neck and shoulders while linking slow head circles to the breath.', cue: 'Sit comfortably tall. Inhale as you roll your head back and around one side, exhale as you roll it forward and around the other. Keep the circle small and smooth.', modification: 'Make the circle smaller, or sway the head gently side to side with the breath. Rest in easy seat if you feel dizzy or uncomfortable.', sided: true },
  { id: 'seated-twist', name: 'Seated Twist', sanskrit: 'Ardha Matsyendrasana', focus: ['Spine', 'Hips'], difficulty: 'Beginner', benefit: 'Encourages spinal rotation and ease through the hips and upper back.', cue: 'Sit tall, then gently rotate your torso. Place one hand behind you and the other on your opposite knee, keeping both sitting bones grounded.', modification: 'Keep your bottom hand on your thigh and turn only as far as feels comfortable.', sided: true },
  { id: 'butterfly', name: 'Butterfly', sanskrit: 'Baddha Konasana', focus: ['Hips', 'Rest'], difficulty: 'Beginner', benefit: 'Invites a gentle opening through the inner thighs and hips.', cue: 'Bring the soles of your feet together and let your knees open naturally. Sit tall without pressing your knees down.', modification: 'Support each knee with a cushion and move your feet farther from your body.' },
  { id: 'butterfly-fold', name: 'Butterfly Fold', sanskrit: 'Baddha Konasana (fold)', focus: ['Hips', 'Rest', 'Spine'], difficulty: 'Beginner', benefit: 'Deepens the inner-thigh and hip opening while easing the back and inviting a settled, inward focus.', cue: 'From Butterfly, hinge forward from your hips with a long spine. Let your head and arms relax toward the mat without forcing your knees down.', modification: 'Support your knees with cushions, sit on a folded blanket, or rest your forehead on a block.' },
  { id: 'pigeon', name: 'Pigeon Pose', sanskrit: 'Eka Pada Rajakapotasana', focus: ['Hips', 'Rest'], difficulty: 'Intermediate', benefit: 'Deeply opens the outer hips and glutes while inviting a settled, supported rest.', cue: 'From all fours, bring one knee toward the same-side wrist and extend the other leg straight back. Keep your hips level and choose how far to fold.', modification: 'Place a cushion or folded blanket under the front hip, or stay upright instead of folding forward.', sided: true },
  { id: 'legs-up-wall', name: 'Legs Up the Wall', sanskrit: 'Viparita Karani', focus: ['Rest'], difficulty: 'Beginner', benefit: 'Invites a gentle inversion that helps the body settle and the mind quiet down.', cue: 'Lie on your back with your hips near the wall and let your legs rest straight up. Allow your arms to rest comfortably beside you.', modification: 'Rest your legs on a chair seat instead of a wall, or bend your knees.' },
  { id: 'savasana', name: 'Resting Pose', sanskrit: 'Savasana', focus: ['Rest', 'Full body'], difficulty: 'Beginner', benefit: 'Makes room for stillness and a gradual close to your practice.', cue: 'Lie comfortably on your back. Let your legs and arms rest apart and allow your breath to feel natural.', modification: 'Place a cushion under your knees, lie on your side, or rest in a chair.' },
  { id: 'warrior-three', name: 'Warrior III', sanskrit: 'Virabhadrasana III', focus: ['Balance', 'Strength'], difficulty: 'Intermediate', benefit: 'Builds single-leg strength and steady focus while lengthening through the back body.', cue: 'From standing, hinge forward and lift one leg behind you until your body forms a long line from heel to head. Reach your arms forward.', modification: 'Keep your hands on blocks or the floor, and keep your lifted leg lower.', sided: true },
  { id: 'crescent-lunge', name: 'Crescent Lunge', sanskrit: 'Anjaneyasana', focus: ['Hips', 'Strength'], difficulty: 'Beginner', benefit: 'Opens the front of the back hip and builds steadiness in the legs.', cue: 'From a lunge, keep your front knee over your ankle and rest your back knee down. Reach your arms up and let your hips settle forward.', modification: 'Pad your back knee and keep your hands on your front thigh.', sided: true },
  { id: 'extended-side-angle', name: 'Extended Side Angle', sanskrit: 'Utthita Parsvakonasana', focus: ['Hips', 'Strength'], difficulty: 'Intermediate', benefit: 'Strengthens the legs and opens the side body and hips.', cue: 'From warrior II, lean forward and rest your forearm or hand on your front thigh or the floor. Reach your other arm up and over.', modification: 'Rest your elbow on your thigh instead of reaching for the floor.', sided: true },
  { id: 'half-moon', name: 'Half Moon', sanskrit: 'Ardha Chandrasana', focus: ['Balance', 'Hips'], difficulty: 'Intermediate', benefit: 'Challenges balance while opening the hips and side body.', cue: 'From a forward fold or triangle, lift one leg and reach your hand to the floor or a block, opening your chest toward the side.', modification: 'Keep your bottom hand on a block and your lifted foot lower.', sided: true },
  { id: 'eagle', name: 'Eagle', sanskrit: 'Garudasana', focus: ['Balance', 'Hips'], difficulty: 'Intermediate', benefit: 'Builds single-leg balance and releases the outer hips and shoulders.', cue: 'Wrap one thigh over the other and cross your arms in front. Sit back as if into a chair and find a steady gaze.', modification: 'Keep your toes on the floor and hug your shoulders instead of wrapping your arms.', sided: true },
  { id: 'garland', name: 'Garland Pose', sanskrit: 'Malasana', focus: ['Hips', 'Rest'], difficulty: 'Beginner', benefit: 'Gently opens the hips and ankles while grounding through the feet.', cue: 'Squat with your feet comfortably wide, press your elbows inside your knees, and bring your palms together at your chest.', modification: 'Sit on a block or keep your heels lifted.' },
  { id: 'upward-dog', name: 'Upward-Facing Dog', sanskrit: 'Urdhva Mukha Svanasana', focus: ['Spine', 'Strength'], difficulty: 'Intermediate', benefit: 'Strengthens the arms and opens the chest and front of the body.', cue: 'Press through your hands and the tops of your feet, lifting your thighs and chest. Keep your shoulders over your wrists and your neck long.', modification: 'Keep your knees down in a low cobra instead, or lift your thighs only a little.' },
  { id: 'sphinx', name: 'Sphinx', sanskrit: 'Salamba Bhujangasana', focus: ['Spine', 'Rest'], difficulty: 'Beginner', benefit: 'Gently mobilizes the upper back without weight on the hands.', cue: 'Lie on your belly with forearms on the mat, elbows under shoulders. Press gently through your forearms and lengthen through your spine.', modification: 'Keep your elbows forward of your shoulders and lift only a little.' },
  { id: 'locust', name: 'Locust', sanskrit: 'Salabhasana', focus: ['Spine', 'Strength'], difficulty: 'Intermediate', benefit: 'Strengthens the back body and encourages a lifted chest and legs.', cue: 'Lie on your belly and lift your chest and legs away from the mat. Reach your arms back along your sides and breathe steadily.', modification: 'Lift just your chest, or keep your legs resting on the mat.' },
  { id: 'camel', name: 'Camel', sanskrit: 'Ustrasana', focus: ['Spine', 'Hips'], difficulty: 'Intermediate', benefit: 'Opens the front of the body and encourages a supported backbend.', cue: 'Kneel with your knees hip-width apart, reach back toward your heels, and lift your chest as you gently press your hips forward.', modification: 'Keep your hands on your lower back instead of reaching for your heels.' },
  { id: 'knees-to-chest', name: 'Knees to Chest', sanskrit: 'Apanasana', focus: ['Rest', 'Spine'], difficulty: 'Beginner', benefit: 'Soothes the lower back and encourages a gentle release.', cue: 'Lie on your back and hug your knees toward your chest. Rock gently from side to side if that feels good.', modification: 'Hug one knee at a time, or rest your feet on the mat.' },
  { id: 'happy-baby', name: 'Happy Baby', sanskrit: 'Ananda Balasana', focus: ['Hips', 'Rest'], difficulty: 'Beginner', benefit: 'Gently opens the hips and inner groins from a supported supine position.', cue: 'Lie on your back, bend your knees toward your armpits, and hold the outer edges of your feet with your ankles over your knees.', modification: 'Hold behind your thighs instead of your feet.' },
  { id: 'reclined-twist', name: 'Reclined Twist', sanskrit: 'Supta Matsyendrasana', focus: ['Spine', 'Rest'], difficulty: 'Beginner', benefit: 'Encourages gentle spinal rotation and releases the lower back.', cue: 'Lie on your back, draw your knees toward your chest, and let them fall to one side while your shoulders stay on the mat.', modification: 'Place a cushion between your knees and keep the twist small.', sided: true },
  { id: 'figure-four', name: 'Figure Four', sanskrit: 'Reclined Pigeon', focus: ['Hips', 'Rest'], difficulty: 'Beginner', benefit: 'Opens the outer hip without weight on the knees.', cue: 'Lie on your back and cross one ankle over the opposite thigh. Thread your hands behind the supporting thigh and draw it toward you.', modification: 'Keep your bottom foot on the mat instead of lifting it.', sided: true },
  { id: 'bird-dog', name: 'Bird Dog', sanskrit: 'Dandayamana Bharmanasana', focus: ['Balance', 'Spine'], difficulty: 'Beginner', benefit: 'Builds core stability and coordination through opposite arm and leg reach.', cue: 'From all fours, extend one arm forward and the opposite leg back, keeping your hips level and your spine long.', modification: 'Lift just your arm or just your leg, or keep your toes on the mat.', sided: true },
]

export const poseById = new Map(poses.map(pose => [pose.id, pose]))
export const focuses: Focus[] = ['Full body', 'Hips', 'Spine', 'Balance', 'Strength', 'Rest']
