export type Focus = 'Full body' | 'Hips' | 'Spine' | 'Balance' | 'Strength' | 'Rest'
export type Difficulty = 'Beginner' | 'Intermediate'

export interface Pose {
  id: string
  name: string
  sanskrit: string
  focus: Focus[]
  difficulty: Difficulty
  benefit: string
  cue: string
  modification: string
  sided?: boolean
}

export const poses: Pose[] = [
  { id: 'mountain', name: 'Mountain', sanskrit: 'Tadasana', focus: ['Balance', 'Full body'], difficulty: 'Beginner', benefit: 'Builds awareness of posture, grounding, and even weight distribution.', cue: 'Stand tall with feet comfortably apart. Soften your knees, relax your shoulders, and let your arms rest by your sides.', modification: 'Stand near a wall or hold the back of a chair for support.' },
  { id: 'upward-salute', name: 'Upward Salute', sanskrit: 'Urdhva Hastasana', focus: ['Spine', 'Full body'], difficulty: 'Beginner', benefit: 'Encourages length through the sides of the body and gentle shoulder mobility.', cue: 'From standing, reach your arms up without lifting your shoulders toward your ears. Keep your ribs relaxed.', modification: 'Keep your hands apart or lift your arms only as high as feels easy.' },
  { id: 'forward-fold', name: 'Standing Forward Fold', sanskrit: 'Uttanasana', focus: ['Spine', 'Hips'], difficulty: 'Beginner', benefit: 'Gently lengthens the back of the legs and invites the upper body to release.', cue: 'Hinge from your hips with bent knees. Let your head and arms hang, keeping your weight balanced through your feet.', modification: 'Rest your hands on blocks or a chair. Bend your knees generously.' },
  { id: 'downward-dog', name: 'Downward-Facing Dog', sanskrit: 'Adho Mukha Svanasana', focus: ['Full body', 'Strength'], difficulty: 'Beginner', benefit: 'Builds upper-body support and lengthens the spine and back of the legs.', cue: 'Press through your hands and lift your hips up and back. Keep your spine long; your heels do not need to touch the mat.', modification: 'Bend your knees, or place your hands on a sturdy chair instead of the floor.' },
  { id: 'plank', name: 'Plank', sanskrit: 'Phalakasana', focus: ['Strength', 'Full body'], difficulty: 'Intermediate', benefit: 'Develops coordinated strength through the shoulders, core, and legs.', cue: 'Place your shoulders over your wrists. Reach back through your heels and keep your neck in line with your spine.', modification: 'Lower your knees to the mat or practice with your hands on a wall.' },
  { id: 'cobra', name: 'Low Cobra', sanskrit: 'Bhujangasana', focus: ['Spine', 'Strength'], difficulty: 'Beginner', benefit: 'Gently mobilizes the upper back and opens the front of the chest.', cue: 'Lie on your belly with hands beside your ribs. Gently lift your chest, keeping elbows bent and little weight in your hands.', modification: 'Lift only a little. Keep your gaze down and stop if your lower back feels compressed.' },
  { id: 'cat', name: 'Cat', sanskrit: 'Marjaryasana', focus: ['Spine'], difficulty: 'Beginner', benefit: 'Encourages gentle spinal flexion and awareness of the back body.', cue: 'On all fours, press the floor away and round your back. Let your head follow naturally without forcing your chin down.', modification: 'Pad your knees or practice seated with hands resting on your thighs.' },
  { id: 'cow', name: 'Cow', sanskrit: 'Bitilasana', focus: ['Spine'], difficulty: 'Beginner', benefit: 'Encourages gentle spinal extension and openness across the chest.', cue: 'On all fours, gently tip your sitting bones up and broaden your chest. Keep the back of your neck long.', modification: 'Use a smaller movement or practice seated. Avoid sinking into your lower back.' },
  { id: 'child', name: 'Child’s Pose', sanskrit: 'Balasana', focus: ['Rest', 'Hips', 'Spine'], difficulty: 'Beginner', benefit: 'Offers a quiet resting shape with gentle length through the back.', cue: 'Bring your hips toward your heels and rest your torso forward. Reach your arms out or rest them beside you.', modification: 'Place a cushion under your forehead or between your hips and heels. Choose a seated rest if kneeling is uncomfortable.' },
  { id: 'warrior-one', name: 'Warrior I', sanskrit: 'Virabhadrasana I', focus: ['Strength', 'Hips', 'Balance'], difficulty: 'Intermediate', benefit: 'Builds standing stability and length through the front of the back hip.', cue: 'Step one foot back, bend your front knee toward your toes, and reach up. Let your hips face forward only as far as comfortable.', modification: 'Shorten your stance and keep hands on hips. Lift the back heel if needed.', sided: true },
  { id: 'warrior-two', name: 'Warrior II', sanskrit: 'Virabhadrasana II', focus: ['Strength', 'Hips', 'Balance'], difficulty: 'Beginner', benefit: 'Develops leg endurance, steady balance, and openness through the hips.', cue: 'Take a wide stance, turn your front toes out, and bend that knee in line with your toes. Open your arms and look past your front hand.', modification: 'Use a shorter stance or support yourself with a chair.', sided: true },
  { id: 'triangle', name: 'Triangle', sanskrit: 'Trikonasana', focus: ['Hips', 'Balance', 'Spine'], difficulty: 'Intermediate', benefit: 'Encourages length through the side body and stability in the legs.', cue: 'From a wide stance, turn your front toes out and reach forward. Rest your lower hand on your shin or a block and open your chest.', modification: 'Keep a soft bend in your front knee and your upper hand on your hip.', sided: true },
  { id: 'tree', name: 'Tree', sanskrit: 'Vrksasana', focus: ['Balance', 'Hips'], difficulty: 'Beginner', benefit: 'Practices single-leg balance, concentration, and standing stability.', cue: 'Shift into one foot. Place your other foot at your ankle or inner calf, away from the knee joint. Find a steady point to look at.', modification: 'Keep the lifted toes on the floor and use a wall for balance.', sided: true },
  { id: 'bridge', name: 'Bridge', sanskrit: 'Setu Bandha Sarvangasana', focus: ['Spine', 'Strength'], difficulty: 'Beginner', benefit: 'Engages the back of the body and gently opens the front of the hips.', cue: 'Lie on your back, knees bent and feet hip-width apart. Press into your feet and lift your hips without turning your head.', modification: 'Lift only as far as comfortable, or keep your hips resting on the mat.' },
  { id: 'seated-fold', name: 'Seated Forward Fold', sanskrit: 'Paschimottanasana', focus: ['Hips', 'Spine'], difficulty: 'Beginner', benefit: 'Gently lengthens the back of the legs and supports a quieter pace.', cue: 'Sit tall with legs in front. Bend your knees and tip forward from the hips, keeping space through your chest.', modification: 'Sit on a folded blanket. Loop a strap around your feet without pulling.' },
  { id: 'easy-seat', name: 'Easy Seat', sanskrit: 'Sukhasana', focus: ['Rest', 'Hips'], difficulty: 'Beginner', benefit: 'Creates a comfortable base for breath awareness and quiet attention.', cue: 'Sit cross-legged with your spine comfortably tall. Let your hands and shoulders soften.', modification: 'Sit on a cushion or in a chair with your feet resting on the floor.' },
  { id: 'butterfly', name: 'Butterfly', sanskrit: 'Baddha Konasana', focus: ['Hips', 'Rest'], difficulty: 'Beginner', benefit: 'Invites a gentle opening through the inner thighs and hips.', cue: 'Bring the soles of your feet together and let your knees open naturally. Sit tall without pressing your knees down.', modification: 'Support each knee with a cushion and move your feet farther from your body.' },
  { id: 'savasana', name: 'Resting Pose', sanskrit: 'Savasana', focus: ['Rest', 'Full body'], difficulty: 'Beginner', benefit: 'Makes room for stillness and a gradual close to your practice.', cue: 'Lie comfortably on your back. Let your legs and arms rest apart and allow your breath to feel natural.', modification: 'Place a cushion under your knees, lie on your side, or rest in a chair.' },
]

export const poseById = new Map(poses.map(pose => [pose.id, pose]))
export const focuses: Focus[] = ['Full body', 'Hips', 'Spine', 'Balance', 'Strength', 'Rest']
